# Generated by Django 2.1.7 on 2019-02-13 14:22

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='博客标题')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='博客标签')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='博客描述')),
                ('headpicture', models.ImageField(blank=True, default='', null=True, upload_to='uploads/blog/images/', verbose_name='封面图片')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='文章正文')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Leacot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myblog.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='', upload_to='uploads/photos/images/')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='照片标题')),
                ('place', models.CharField(max_length=60, verbose_name='拍摄地址')),
                ('time', models.DateTimeField(null=True, verbose_name='拍摄时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '相册',
                'verbose_name_plural': '相册 ',
                'ordering': ['-update_time'],
            },
        ),
    ]
